DROP TABLE IF EXISTS CustomerHistory;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS PharmacyStaff;
DROP TABLE IF EXISTS Supply;
DROP TABLE IF EXISTS Medication;
DROP TABLE IF EXISTS Supplier;
DROP TABLE IF EXISTS Pharmacy;